### ISSUE TITLE
install error : No such kernel named .net-csharp

### ISSUE THREAD

**Issue by akamonet** [GlebSBrykin/DotNetInGoogleColab#1]
when I run the first cell, I got an error :

"NoSuchKernel: No such kernel named .net-csharp"

![image](https://github.com/GlebSBrykin/DotNetInGoogleColab/assets/14997795/8e6d676d-31f6-4a6b-9969-197d05f331c8)

**Comment by GlebSBrykin** [comment]
Good afternoon, indeed, there is a problem. Thanks for the information. The reason is to update Linux in Google Colab. This template is designed for Ubuntu 20.04, and Google Colab is now 22.04. At the moment, the templates are updated and successfully install the C# or F# kernel in Google Colab.
